const swaggerAutogen = require('swagger-autogen')()


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:1400",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        },
        {
            "name": "Category",
            "description": "Category Endpoints"
        },
        {
            "name": "Donation",
            "description": "Donation Endpoints"
        }
        {
            "name": "Donar",
            "description": "Doner Endpoints"
        }
    ],
    securityDefinitions: {
        apiKeyAuth: {
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "X-API-KEY",  // name of the header, query parameter or cookie
            description: "any description..."
        }
    },
    definitions: {

        AddUser: {
            $first_name: "John",
            $surname: "Doe",
            email: "email@example.com",
            phone: "07279797819",
            password: "passwordexample#com",
            password_confirm: "passwordexample#com"
        },
        LoginUser: {
            email: "email@example.com",
            password: "passwordexample#com",
        },
        AddCategory: {
            name: "sample category",

        },
        EditCategory: {
            name: "sample category",

        },
        AddDonation: {
            name: "sample Donation",
            category_id: "60406e9a5a75fd34144f7451",

        },
        EditDonation: {
            name: "sample Donation",
            category_id: "60406e9a5a75fd34144f7451",
        }
    }
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./server.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./server')           // Your project's root file
})
